### ISSUE TITLE
5.15 stabilized 

### ISSUE THREAD

**Issue by oofdog** [feniksa/gentoo_ACS_override_patch#10]

**Comment by feniksa** [comment]
@oofdog I haven't available my hardware that requires ACS override patch. I can blindly port patch to 5.15 kernel, but need someone to check

**Comment by EtherAura** [comment]
@feniksa I will be able to test on my X470 system. I have been using your 5.10 patch. I am passing through several PCI devices, (including GPU) to a W10 VM via KVM+virt-manager with no observed issues.

**Comment by feniksa** [comment]
@EtherAura  https://github.com/feniksa/gentoo_ACS_override_patch/pull/11  

Please, try this patchset (branch kernel-5.15.11). I blindly port changes from prev. kernel.

**Comment by feniksa** [comment]
+ @oofdog  @EtherAura guys, please, may someone check on kernel 5.15.11 fix from #11

**Comment by EtherAura** [comment]
@feniksa I will check tonight. Time is somewhat limited during the week. I will keep you updated.

**Comment by feniksa** [comment]
@EtherAura Thanks a lot for help

**Comment by EtherAura** [comment]
@feniksa I've built with a clean `genkernel --install all`, and everything appears to be working well! if there are any specific tests anyone would like me to preform, just let me know.

**Comment by feniksa** [comment]
@EtherAura Thanks a lot for testing. PR merged
