### ISSUE TITLE
Uninstall patch

### ISSUE THREAD

**Issue by anklav24** [feniksa/gentoo_ACS_override_patch#13]
Can I undo the changes if I use this patch?

**Comment by feniksa** [comment]
Yes, you can.

To undo changes:

1.  Remove /etc/portage/patches/sys-kernel
2.  Recompile kernel. For example: genkernel all
3.  Don't forget to install kernel to /boot/ (if your genkernel doesn't configure to do that or in case of manual compilation)
4.  Reboot to new kernel

**Comment by anklav24** [comment]
Thank you so much!
