### ISSUE TITLE
5.4.97 stable

### ISSUE THREAD

**Issue by SleepyMario** [feniksa/gentoo_ACS_override_patch#3]
Hello, I can't code myself so it's not possible for me to contribute or help with this, but I'd like to mention that 5.4.97 has been stable for a while. 

Thanks for your work!

**Comment by feniksa** [comment]
Hi @SleepyMario , 

Thank you for notify about 5.4.97. I push patch for 5.4.97 and it is tested for 1w+ and it should work without problesm. 

P.S. I forgot to update git repo with it

Thanks
